version: '3'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    user: "1000"
  db:
    image: postgres:11.1-alpine
    # volumes:
    #   - db:/var/lib/postgresql/data:rw
  adminer:
    image: adminer
    ports:
      - 8080:8080
# volumes:
#   db: {}